version: 0.0
os: linux
files:
   - source: /
     destination: /api-server
permissions:
   - object: /
     pattern: "**"
     owner: ubuntu
     mode: 755
     type:
       - file
hooks:
   BeforeInstall:
    - location: deployment_scripts/install_node.sh
      runas: root
   AfterInstall:
    - location: deployment_scripts/start_api_server.sh
      runas: root
